version: '3.7'

services:
  mailhog-broadcasting:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  zookeeper-broadcasting:
    image: confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper-broadcasting
    container_name: zookeeper-broadcasting
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker-broadcasting:
    image: confluentinc/cp-kafka:5.4.0
    hostname: broker-broadcasting
    container_name: broker-broadcasting
    depends_on:
      - zookeeper-broadcasting
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-broadcasting:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-broadcasting:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  flowable-db-broadcasting:
    image: postgres:10
    container_name: postgress-broadcasting
    ports:
      - 5432:5432
    volumes:
      - data_db:/var/lib/postgresql/data_broadcasting
    environment:
      - POSTGRES_DB=flowable-db-broadcasting
      - POSTGRES_USER=flowable
      - POSTGRES_PASSWORD=flowable

  flowable-modeler-broadcasting:
    image: flowable/flowable-modeler:6.5.0
    container_name: flowable-modeler-broadcasting
    ports:
      - 8091:8888
    environment:
      - SERVER_PORT=8888
      - SERVER_SERVLET_CONTEXT-PATH=/
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db-broadcasting:5432/flowable-db-broadcasting
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - FLOWABLE_COMMON_APP_IDM-URL=http://flowable-idm-broadcasting:8080
      - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://localhost:8093
      - FLOWABLE_COMMON_APP_IDM-ADMIN.USER=admin
      - FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=test
      - FLOWABLE_MODELER_APP_DEPLOYMENT-API-URL=http://flowable-task-broadcasting:9999/flowable-task/app-api

  flowable-admin-broadcasting:
    image: flowable/flowable-admin:6.5.0
    container_name: flowable-admin-broadcasting
    ports:
      - 8092:9988
    environment:
      - SERVER_PORT=9988
      - SERVER_SERVLET_CONTEXT-PATH=/
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db-broadcasting:5432/flowable-db-broadcasting
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - FLOWABLE_COMMON_APP_IDM-URL=http://flowable-idm-broadcasting:8080
      - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://localhost:8093
      - FLOWABLE_COMMON_APP_IDM-ADMIN.USER=admin
      - FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=test
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_SERVER-ADDRESS=http://host.docker.internal
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_PORT=8090
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_CONTEXT-ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_REST-ROOT=process-api
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_SERVER-ADDRESS=http://host.docker.internal
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_PORT=8090
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_CONTEXT-ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_REST-ROOT=cmmn-api
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_SERVER-ADDRESS=http://host.docker.internal
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_PORT=8090
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_CONTEXT-ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_REST-ROOT=dmn-api
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_SERVER-ADDRESS=http://host.docker.internal
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_PORT=8090
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_CONTEXT-ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_REST-ROOT=form-api
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_SERVER-ADDRESS=http://host.docker.internal
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_PORT=8090
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_CONTEXT-ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_REST-ROOT=content-api
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_SERVER-ADDRESS=http://host.docker.internal
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_PORT=8090
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_CONTEXT-ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_REST-ROOT=app-api

  flowable-idm-broadcasting:
    image: flowable/flowable-idm:6.5.0
    container_name: flowable-idm-broadcasting
    ports:
      - 8093:8080
    environment:
      - SERVER_PORT=8080
      - SERVER_SERVLET_CONTEXT-PATH=/
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db-broadcasting:5432/flowable-db-broadcasting
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable

  flowable-task-broadcasting:
    image: flowable/flowable-task:6.5.0
    container_name: flowable-task-broadcasting
    ports:
      - 8094:9999
    environment:
      - SERVER_PORT=9999
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db-broadcasting:5432/flowable-db-broadcasting
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - FLOWABLE_COMMON_APP_IDM-URL=http://flowable-idm-broadcasting:8080
      - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://localhost:8093
      - FLOWABLE_COMMON_APP_IDM-ADMIN.USER=admin
      - FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=test
      - FLOWABLE_TASK_APP_KAFKA-ENABLED=false
      - FLOWABLE_PROCESS_ASYNC_EXECUTOR_AUTO-ACTIVATE=false
      - FLOWABLE_CMMN_ASYNC_EXECUTOR_AUTO-ACTIVATE=false
      - FLOWABLE_PROCESS_ASYNC-HISTORY_EXECUTOR_AUTO-ACTIVATE=false
      - FLOWABLE_PROCESS_ASYNC_EXECUTOR-ACTIVATE=false
      - FLOWABLE_CMMN_ASYNC_EXECUTOR-ACTIVATE=false
      - FLOWABLE_PROCESS_ASYNC_EXECUTOR_ENABLED=false
      - FLOWABLE_CMMN_ASYNC_EXECUTOR_ENABLED=false
      - FLOWABLE_ASYNC-EXECUTOR-ACTIVATE=false
      - FLOWABLE_EVENTREGISTRY_ENABLED=false

volumes:
  data_db: